# Generated by Django 3.1 on 2021-10-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210421_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='open',
            field=models.BooleanField(default=True, help_text='marks a poll open or closed'),
        ),
    ]
