# Generated by Django 3.1 on 2021-10-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211015_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed',
            field=models.BooleanField(default=False, help_text='marks a poll as closed'),
        ),
    ]
